-- AlterTable
ALTER TABLE "Airline" ALTER COLUMN "ALname" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "Booking" ALTER COLUMN "source" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "destination" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "Employee" ALTER COLUMN "firstName" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "lastName" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "cardName" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "airlineFlights" ALTER COLUMN "cityFrom" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "cityTo" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "stoppedFlights" ALTER COLUMN "stoppingAirportName" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "stoppingAirportCountry" SET DATA TYPE VARCHAR(50);
